# Generated by Django 5.0.6 on 2024-07-10 07:28

import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('name_eng', models.CharField(max_length=255)),
                ('script', models.TextField()),
                ('review_lst', djongo.models.fields.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('review_lst', djongo.models.fields.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('written_id', models.CharField(max_length=255)),
                ('coffee_id', models.CharField(max_length=255)),
                ('note_floral', models.BooleanField(default=False)),
                ('note_fruit', models.BooleanField(default=False)),
                ('note_berry', models.BooleanField(default=False)),
                ('note_nut', models.BooleanField(default=False)),
                ('note_choco', models.BooleanField(default=False)),
                ('note_cereal', models.BooleanField(default=False)),
                ('taste_sweet', models.IntegerField()),
                ('taste_sour', models.IntegerField()),
                ('taste_bitter', models.IntegerField()),
                ('taste_body', models.IntegerField()),
                ('overall_score', models.IntegerField()),
                ('feeling', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
